graph TD

subgraph economy
development[infra/tech/knowledge]

corporations -->|owns| animals
corporations -->|owns| land

animals -->|work| jobs
animals -->|VOICE CREDITS| corporations
land -->|creates| jobs

jobs -->|generates| resources
resources -->|creates| development
development -->|improves| jobs
development -->|equals| growth

rules{RULES}
funding{GRANTS}
end

subgraph governance
corporations -->|taxes| government
government -->|creates| policies
corporations -->|votes on| policies
policies -->|sets| rules
policies -->|funds| funding
end
